before:
  hooks:
    - dep ensure

project_name: removebg

builds:
  -
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows

archives:
  -
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  skip: true

brews:
  -
    name: removebg
    github:
      owner: remove-bg
      name: homebrew-tap
    homepage: "https://www.remove.bg/"
    description: "Remove image background - 100% automatically"

nfpms:
  -
    vendor: Kaleido AI GmbH
    homepage: "https://www.remove.bg/"
    description: "Remove image background - 100% automatically"
    formats:
      - deb
      - rpm
